# Generated by Django 3.2.9 on 2021-11-13 21:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_images_drink'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='drink',
            name='allergy',
        ),
    ]
