# Generated by Django 3.2.9 on 2021-11-13 21:09

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='images',
            name='drink',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.drink'),
            preserve_default=False,
        ),
    ]
